### PR TITLE
2.8.0

### LINKED ISSUE #168: Swap out the screenshot of the Crio Starter Content with an actual screenshot of their site
Swap out the screenshot of the Crio Starter Content with an actual screenshot of their site

### LINKED ISSUE #185: [Bug] Image purchase fails with error 'No local cost data'
**Describe the bug**
When attempting to purchase an image with bg copyright coins, customer is receiving error 'Error: We have no local cost data'

**To Reproduce**
In some edge cases local_publish_cost_data is set but is empty

### PR DESCRIPTION
**Pull request by jamesros161**
# 2.8.0 ChangeLog #
* New Feature: Added onboarding checklist to help users get started with Inspirations.
* New Feature: Theme screenshot now displays the specific Crio theme design chosen 
** Resolves #168
* Bug Fix: Image purchase fails with error 'No local cost data'
** Resolves #185

# Testing Instructions #
1. Install Zip from file linked here: [boldgrid-inspirations-2.8.0-rc.1.zip](https://github.com/BoldGrid/boldgrid-inspirations/files/12849229/boldgrid-inspirations-2.8.0-rc.1.zip)

2. If Installing the zip on an existing install, Ensure that the My Inspirations page is replaced with the new onboarding process, and that a percentage is shown for the progress. Otherwise proceed with a new inspiration, or start over the existing one. The "Start Over" button has been relocated to the 'Choose Your Theme' task in the left most column.
3. Proceed through the Inspirations process. You will likely want to repeat this a few times testing traditional Crio themes, as well as themes that use the Custom Page Headers, and with / without a blog. as the cards added will be different
4. Ensure that upon completing an Inspirations theme deployment, that the new Onboarding checklist is show in place of the old My Inspirations page.
5. Ensure that the screenshot shown reflects the theme you chose.
6. Ensure that the cards shown make sense regarding the choices you chose in the deployment process ( Blog, Headers, Sprout, W3TC, etc ).
7. Ensure that all buttons and links work and that they link to the appropriate location.
8. Ensure that progress updates when a task is marked complete / incomplete, and that the progress saves when leaving / returning to the page.

### CODE REVIEW

File: assets/js/my-inspiration.js [hunk 1]
```diff
@@ -1,17 +1,180 @@
...
+	 * 
+	 * @since 2.8.0
+	 * 
+	 * @param {float} completedDecimal The percentage of tasks completed
+	 * 
+	 * @return {string} The formatted progress
+	 */
+	var formatProgress = ( completedDecimal ) => {
+		return Math.round( completedDecimal * 100 ) + '%';
+	}
```
Comment (bwmarkle) [inline assets/js/my-inspiration.js:24]: Consistency. Should add a space after this function.

File: includes/class-boldgrid-inspirations-config.php [hunk 2]
```diff
@@ -77,6 +77,12 @@ public static function get_format_configs() {
 			$local_configs = require $local_config_filename;
 		}
 
+		// Onboarding configs
+		if ( file_exists( $config_dir . '/config.onboarding.php' ) ) {
+			$onboarding_configs = require $config_dir . '/config.onboarding.php';
+			$local_configs = array_merge( $local_configs, $onboarding_configs );
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-config.php:83]: Equal signs do not match up.

```php
			$onboarding_configs = require $config_dir . '/config.onboarding.php';
			$local_configs = array_merge( $local_configs, $onboarding_configs );
```

File: includes/class-boldgrid-inspirations-dashboard.php [hunk 3]
```diff
@@ -116,18 +116,72 @@ public function add_hooks() {
...
+		// Verify user is logged in.
+		if ( ! is_user_logged_in() || ! current_user_can( 'manage_options' ) ) {
+			return;
+		}
+
+		if ( false === $progress &&
+			empty( get_option( $config['onboarding_tasks_option'] ) ) &&
+			! empty( get_option( 'boldgrid_install_options' ) ) ) {
+
+			$this->create_onboarding_tasks( get_option( 'boldgrid_install_options' ) );
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-dashboard.php:137]: Does this mean we only create tasks once, after the user has completed a deployment? If so, what if we wanted to add a new item to the checklist in 2 weeks?

File: includes/class-boldgrid-inspirations-dashboard.php [hunk 4]
```diff
@@ -116,18 +116,72 @@ public function add_hooks() {
...
+		// Verify that there is a valid progress to display.
+		if ( false === $progress ) {
+			return;
+		}
+
+		$progress = round( $progress, 2 );
+
+		$formatted_progress = sprintf( '%.0f%%', (float) $progress * 100 );
+
+		$class = '';
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-dashboard.php:151]: Is this variable `$class` actually used?

File: includes/class-boldgrid-inspirations-onboarding-progress.php [hunk 5]
```diff
@@ -0,0 +1,209 @@
...
+	 * Get Task.
+	 *
+	 * @since 2.8.0
+	 *
+	 * @param string $task_id The task ID.
+	 *
+	 * @return array The task object.
+	 */
+	public function get_task( $task_id ) {
+		$tasks = get_option( $this->tasks_option_name );
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-onboarding-progress.php:78]: This set of code is duplicated several times.

```php
$tasks = get_option( $this->tasks_option_name );

if ( ! is_array( $tasks ) ) {
	return false;
}
```

What if we create a method get_tasks?

```php
function get_tasks() {
    $tasks = get_option( $this->tasks_option_name );

    return is_array( $tasks ) ? $tasks : array();
}
```

File: includes/class-boldgrid-inspirations-onboarding-progress.php [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+		}
+
+		if ( ! current_user_can( 'manage_options' ) ) {
+			wp_send_json_error( 'invalid_permissions' );
+		}
+
+		$task_id = isset( $_POST['task_id'] ) ? sanitize_text_field( wp_unslash( $_POST['task_id'] ) ) : '';
+
+		if ( 'skip_all_tasks' === $task_id ) {
+			$this->skip_all_tasks();
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-onboarding-progress.php:168]: If someone is skipping all tasks, can we return at this point?

Comment (bwmarkle) [reply includes/class-boldgrid-inspirations-onboarding-progress.php:168]: OK, I see the `skip_all_tasks()` function has `wp_send_json_success();`. I would recommend not adding `wp_send_json_success();` to a function that is not solely for handling an ajax request.

File: includes/class-boldgrid-inspirations-onboarding-tasks.php [hunk 7]
```diff
@@ -0,0 +1,258 @@
...
+	 * Get Task
+	 *
+	 * @since 2.8.0
+	 *
+	 * @param string  $task_id       The task ID.
+	 * @param boolean $task_complete Whether the task is complete.
+	 *
+	 * @return array The task config array.
+	 */
+	public function get_task( $task_id, $task_complete ) {
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-onboarding-tasks.php:112]: It seems strange to have a `$task_complete` as a parameter.

For example, if I said `get_post( 123, 'publish' )` as another developer it would be hard to understand why I'm passing a post status to a get_post... It should get post `123` regardless of the status.

File: includes/class-boldgrid-inspirations-onboarding-tasks.php [hunk 8]
```diff
@@ -0,0 +1,258 @@
...
+	/**
+	 * Has Legacy Headers
+	 *
+	 * @since 2.8.0
+	 *
+	 * @param array $install_options
+	 *
+	 * @return boolean True if the theme has legacy headers, false otherwise.
+	 */
+	public function has_legacy_headers( $install_options ) {
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations-onboarding-tasks.php:196]: `has_legacy_headers`, `has_custom_headers`, etc... Are these classes better suited for a utility class or another existing class? What if we need to reuse them? I would never guess that this is the class I should go to to look for these types of methods.

File: includes/class-boldgrid-inspirations.php [hunk 9]
```diff
@@ -318,6 +318,33 @@ private function queue_hooks() {
 				'filter_allowed_html',
 			), 10, 2
 		);
+
+		// Create Onboarding Tasks when deployment is complete.
```
Comment (bwmarkle) [inline includes/class-boldgrid-inspirations.php:322]: I mentioned this before, but it feels like we should be able to add tasks when need be... e.g. a month from now we may realize users really need to do xy&z, we need a way to add that task.

File: includes/class-boldgrid-inspirations-onboarding-progress.php (hunk 6 above)
Comment (jamesros161) [reply includes/class-boldgrid-inspirations-onboarding-progress.php:168]: How would you recommend this then? 
This whole thing is about handling the ajax request. If the $task_id is 'skip_all_tasks' then we want it to execute the code in the skip_all_tasks() method, and then send the success, thus ending the ajax call, and short circuiting the rest of this method

File: includes/class-boldgrid-inspirations-onboarding-tasks.php (hunk 8 above)
Comment (jamesros161) [reply includes/class-boldgrid-inspirations-onboarding-tasks.php:196]: This class is where the actual task objects are generated from the config files, so it makes sense that this is where their logic would live. The location of these methods is also specified in the config itself. Initially I tried adding the logic directly to the config in the form of anonymous functions in the 'active_callback' key, but it didn't like serializing anonymous functions. Alternatively, these functions could be added directly to the beginning of the onboarding.config.php file if you think that'd be better.

File: includes/class-boldgrid-inspirations-onboarding-tasks.php (hunk 7 above)
Comment (jamesros161) [reply includes/class-boldgrid-inspirations-onboarding-tasks.php:112]: The reason for this, is that the config array contains a key that indicates whether it should already be marked complete or not. So when using this method to get the task, we want to use the current competion status when getting the task

File: includes/class-boldgrid-inspirations.php (hunk 9 above)
Comment (jamesros161) [reply includes/class-boldgrid-inspirations.php:322]: I intentionally didn't what that to be a thing.... If we add new items, then it should be something that only gets added on a new install or redeployment. We don't want users to have gone to 100% completion, and then have that number keep changing on them. That would get really really annoying

**Review by bwmarkle — APPROVED** [review]
